### ISSUE TITLE
没有mac 安装包可以下载

### ISSUE THREAD

**Issue by dreambe** [dxmwl/new_bee_upload_app#1]
没有mac 安装包可以下载

**Comment by dxmwl** [comment]
身边没有mac电脑，没办法打包，可以自行打mac版本的

**Comment by dreambe** [comment]
> 身边没有mac电脑，没办法打包，可以自行打mac版本的

一直打包失败。可以在文档中更新一下打包的依赖吗，比如需要哪些环境，跟具体支持的版本

或者说，下载源码后，没有安装compose，仅仅是下载源码后，执行编译chmod +x ./gradlew && ./gradlew packageMac，是否OK，没做过打包这块的事情，希望帮解读下，谢谢

**Comment by dxmwl** [comment]
现在处理好了吗？可以加我微信。帮你远程看一下：dxmcpjl

**Comment by KevinGong2013** [comment]
关于 Mac 打包，可以参考以下环境配置：

1. 安装 **JDK 17**（推荐使用 [Temurin](https://adoptium.net/) 版本）
2. 2. 安装 **Android Studio** ，确保 Kotlin 插件已内置
3. 3. 项目使用 Jetpack Compose Desktop，无需单独安装 Compose，只需保证 Gradle 能正常同步依赖
4. 4. 执行打包命令：
 ```bash
 chmod +x ./gradlew && ./gradlew packageReleaseDmg
 ```
8.    （`packageMac` 可能需改为 `packageReleaseDmg` 或 `packageDmg`，具体 task 名可运行 `./gradlew tasks` 查看）
如果依然打包失败，建议贴出具体报错日志方便进一步排查。

---

另外如果你的需求主要是 **自动上传 APK 到各大应用市场**，可以试试 **[apkgo](https://github.com/KevinGong2013/apkgo)**。它是一个命令行工具，**支持 Mac / Linux / Windows 三平台**，无需图形界面，直接在终端或 CI/CD 中使用，免去打包桌面应用的烦恼 😊
